# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# TODO: Populate this template for CodeRabbit platform
# This template will be populated in a future update to support CodeRabbit-specific configuration.

language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
